"use client";
import {useEffect,useMemo,useState} from "react";
import type {Event} from "@/lib/catalog";
const rows=["A","B","C","D","E","F"], cols=[1,2,3,4,5,6,7,8,9,10];
type Step="home"|"detail"|"seats"|"checkout"|"ticket"|"admin";
export default function ShowSphere(){
 const [events,setEvents]=useState<Event[]>([]),[query,setQuery]=useState(""),[city,setCity]=useState("Bengaluru"),[step,setStep]=useState<Step>("home"),[selected,setSelected]=useState<Event|null>(null),[showtime,setShowtime]=useState("7:45 PM"),[picked,setPicked]=useState<string[]>([]),[taken,setTaken]=useState<string[]>(["A3","A4","B6","C1","C2","D8"]),[hold,setHold]=useState<{token:string;expiresAt:string}|null>(null),[ticket,setTicket]=useState<any>(null),[toast,setToast]=useState("");
 useEffect(()=>{fetch("/api/events").then(r=>r.json()).then(setEvents)},[]);
 useEffect(()=>{if(selected&&step==="seats")fetch("/api/events/"+selected.id+"/seats?showtime="+encodeURIComponent(showtime)).then(r=>r.json()).then(x=>setTaken([...new Set([...x.taken,"A3","A4","B6","C1","C2","D8"])]))},[selected,showtime,step]);
 const filtered=useMemo(()=>events.filter(e=>(e.title+" "+e.genre+" "+e.kind).toLowerCase().includes(query.toLowerCase())),[events,query]);
 const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
 function choose(event:Event){setSelected(event);setPicked([]);setHold(null);setStep("detail");window.scrollTo(0,0)}
 async function reserve(){if(!selected||!picked.length)return;const r=await fetch("/api/holds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:selected.id,showtime,seats:picked})});const data=await r.json();if(!r.ok){setToast(data.error);return}setHold(data);setStep("checkout")}
 async function pay(){if(!selected||!hold)return;const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holdToken:hold.token,eventId:selected.id,showtime})});const d=await r.json();if(!r.ok){setToast(d.error);return}setTicket(d);setStep("ticket")}
 return <main>
 <header><button className="brand" onClick={()=>setStep("home")}><i>●</i> ShowSphere</button><div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for movies, events, plays, sports..."/></div><button className="city" onClick={()=>setCity(city==="Bengaluru"?"Mumbai":"Bengaluru")}>⌖ {city} ▾</button><button className="ghost" onClick={()=>setStep("admin")}>Admin</button></header>
 {toast&&<div className="toast">{toast}<button onClick={()=>setToast("")}>×</button></div>}
 {step==="home"&&<><section className="hero"><div><span className="eyebrow">THE BEST SEATS IN THE HOUSE</span><h1>Your next <em>great night</em><br/>starts here.</h1><p>From blockbuster premieres to intimate live experiences — discover moments worth showing up for.</p><button className="primary" onClick={()=>document.getElementById("discover")?.scrollIntoView({behavior:"smooth"})}>Explore now →</button></div><div className="hero-card"><span>TONIGHT'S PICK</span><h2>Dune: Part Two</h2><p>★★★★★ 8.8/10</p><button onClick={()=>choose(events[0])}>Book tickets</button></div></section>
 <section id="discover" className="content"><div className="section-head"><div><span className="eyebrow">WHAT'S ON</span><h2>Made for your weekend</h2></div><div className="chips"><button className="active">All</button><button>Movies</button><button>Events</button></div></div><div className="grid">{filtered.map(e=><article className="card" key={e.id} onClick={()=>choose(e)}><img src={e.image} alt=""/><div className="card-copy"><span>{e.kind} · {e.genre}</span><h3>{e.title}</h3><p>★ {e.rating} &nbsp; • &nbsp; {e.language}</p><b>From {money(e.price)}</b></div></article>)}</div></section></>}
 {step==="detail"&&selected&&<section className="detail"><button className="back" onClick={()=>setStep("home")}>← Back to discovery</button><div className="detail-layout"><img src={selected.image} alt=""/><div><span className="eyebrow">{selected.kind.toUpperCase()}</span><h1>{selected.title}</h1><p className="meta">★ {selected.rating} &nbsp; · &nbsp; {selected.duration} &nbsp; · &nbsp; {selected.language}</p><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><p className="about">{selected.about}</p><div className="booking-box"><div><b>{selected.date}</b><small>{selected.venue}, {city}</small></div><div className="times">{["10:00 AM","1:15 PM","4:30 PM","7:45 PM","10:50 PM"].map(t=><button className={showtime===t?"chosen":""} onClick={()=>setShowtime(t)} key={t}>{t}</button>)}</div><button className="primary" onClick={()=>setStep("seats")}>Select seats →</button></div></div></div></section>}
 {step==="seats"&&selected&&<section className="seats content"><button className="back" onClick={()=>setStep("detail")}>← Change showtime</button><h2>Select your seats</h2><p>{selected.title} · {showtime} · {selected.venue}</p><div className="legend"><span>□ Available</span><span>■ Selected</span><span>■ Taken</span></div><div className="screen">SCREEN THIS WAY</div><div className="seat-map">{rows.map(r=><div className="seat-row" key={r}><b>{r}</b>{cols.map(c=>{const s=r+c,blocked=taken.includes(s),on=picked.includes(s);return <button disabled={blocked} onClick={()=>setPicked(on?picked.filter(x=>x!==s):[...picked,s])} className={"seat "+(blocked?"taken":on?"selected":"")} key={s}>{c}</button>})}</div>)}</div><div className="sticky"><span>{picked.length?picked.join(", ")+" · "+money(picked.length*selected.price):"Choose up to 10 seats"}</span><button className="primary" disabled={!picked.length} onClick={reserve}>Continue</button></div></section>}
 {step==="checkout"&&selected&&<section className="checkout content"><button className="back" onClick={()=>setStep("seats")}>← Change seats</button><h2>Almost there</h2><div className="checkout-grid"><div className="payment"><h3>Payment</h3><label>Card number<input defaultValue="4242 4242 4242 4242"/></label><div className="two"><label>Expiry<input defaultValue="12/28"/></label><label>CVV<input defaultValue="123"/></label></div><p className="safe">🔒 Demo payment gateway — no actual payment is processed.</p><button className="primary full" onClick={pay}>Pay {money(picked.length*selected.price)}</button></div><aside><img src={selected.image} alt=""/><h3>{selected.title}</h3><p>{showtime} · {selected.date}</p><p>Seats: <b>{picked.join(", ")}</b></p><hr/><b>Total {money(picked.length*selected.price)}</b></aside></div></section>}
 {step==="ticket"&&selected&&ticket&&<section className="ticket-page content"><div className="success">✓</div><span className="eyebrow">BOOKING CONFIRMED</span><h1>You're going!</h1><p>Your tickets are ready. A confirmation has been sent to your email.</p><div className="ticket"><img src={selected.image} alt=""/><div><h2>{selected.title}</h2><p>{selected.venue}</p><div className="ticket-info"><span><small>DATE</small>{selected.date}</span><span><small>TIME</small>{showtime}</span><span><small>SEATS</small>{ticket.seats.join(", ")}</span></div><p className="booking-id">Booking ID: {ticket.id} · {ticket.paymentId}</p></div><div className="qr">▦<small>SCAN AT VENUE</small></div></div><button className="primary" onClick={()=>setStep("home")}>Explore more shows</button></section>}
 {step==="admin"&&<section className="content admin"><button className="back" onClick={()=>setStep("home")}>← Back to storefront</button><span className="eyebrow">OPERATIONS</span><h1>Venue manager</h1><div className="stat-grid"><div><small>TODAY'S REVENUE</small><b>₹ 1,24,860</b><em>↑ 18.2%</em></div><div><small>TICKETS SOLD</small><b>428</b><em>↑ 12.4%</em></div><div><small>ACTIVE SHOWS</small><b>16</b><em>On schedule</em></div></div><h2>Today's performances</h2><table><thead><tr><th>Show</th><th>Time</th><th>Sold</th><th>Status</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.title}</td><td>7:45 PM</td><td>68%</td><td><span className="live">Live</span></td></tr>)}</tbody></table></section>}
 <footer>ShowSphere <span>Built for moments that matter.</span><span>Help · Terms · Privacy</span></footer></main>
}