export type Event={id:string;title:string;kind:"Movie"|"Event";genre:string;rating:string;duration:string;language:string;date:string;venue:string;city:string;image:string;price:number;about:string;tags:string[]};
export const events:Event[]=[
{id:"dune",title:"Dune: Part Two",kind:"Movie",genre:"Sci-Fi · Adventure",rating:"8.8",duration:"2h 46m",language:"English, Hindi",date:"Today",venue:"PVR: Orion Mall",city:"Bengaluru",image:"https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=800&q=80",price:260,about:"Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",tags:["IMAX","Dolby Atmos"]},
{id:"kong",title:"Godzilla x Kong",kind:"Movie",genre:"Action · Sci-Fi",rating:"7.4",duration:"1h 55m",language:"English, Hindi",date:"Today",venue:"INOX: Garuda Mall",city:"Bengaluru",image:"https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",price:220,about:"The epic battle continues as Kong and Godzilla face a colossal undiscovered threat.",tags:["3D","4DX"]},
{id:"arijit",title:"Arijit Singh India Tour",kind:"Event",genre:"Live Music",rating:"9.3",duration:"3h",language:"Hindi",date:"Sat, 31 Aug",venue:"Phoenix Marketcity Arena",city:"Bengaluru",image:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=80",price:1499,about:"An unforgettable live evening with Arijit Singh and a 40-piece orchestra.",tags:["Live","Outdoor"]},
{id:"standup",title:"The Last Laugh",kind:"Event",genre:"Comedy",rating:"8.5",duration:"1h 30m",language:"English",date:"Sun, 1 Sep",venue:"Good Shepherd Auditorium",city:"Bengaluru",image:"https://images.unsplash.com/photo-1527224857830-43a7acc85260?auto=format&fit=crop&w=800&q=80",price:499,about:"A no-holds-barred stand-up special featuring the city’s sharpest comics.",tags:["Comedy","18+"]}
];
export function eventById(id:string){return events.find(e=>e.id===id)}
export const showtimes=["10:00 AM","1:15 PM","4:30 PM","7:45 PM","10:50 PM"];
